### ISSUE TITLE
Database Structuring

### ISSUE THREAD

**Issue by kferko** [kferko/GKMicroBlog#1]
setting up the skeleton/structure
tables for users and restaurants - ability to login with username&password
table for posts from users
ability to add photos of dishes

**Comment by gregoryjpark** [comment]
_This issue will close when the database schema is finished_

#### Classes
- User
- Review (aka Post)
- Owner (aka Restaurants)
- Menu
- Dish
- UserFriendship

#### Tables
- users
  - username
  - password
  - motto
- reviews
  - user_id
  - dish_id
  - rating
  - description
  - photo
- owners
  - username
  - password
  - menu_id
- menus
  - owner_id
  - name
  - address
  - phone
  - description
- dishes
  - menu_id
  - name
  - description
  - price
    -user_friendships
  - user_id
  - user_friend_id

#### Associations

_Users and Reviews_
- One User has many Reviews
- One Review belongs to a User

_Owners and Menus_
- One Owner has one Menu
- One Menu belongs to a Owner

_Menus and Dishes_
- One Menu has many Dishes
- One Dish belongs to a Menu

_Dishes and Reviews_
- One Dish has many Reviews
- One Review belongs to a Dish

_Users and Users_
- One User has many UserFriendships
